#! python3
# Confonet2.py - To scrape data from confonet site


import sys
#sys.path.append('C:\\program files\\anaconda3\\lib\\site-packages\\')
import selenium
import time
import datetime
from datetime import timedelta
import os

from selenium import webdriver
from selenium.webdriver.support.ui import Select
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.common import exceptions
import openpyxl
from openpyxl import Workbook
from openpyxl.styles import Font
import pandas as pd

driver = webdriver.Chrome(executable_path='chromedriver')
driver.get('http://cms.nic.in/ncdrcusersWeb/search.do?method=loadSearchPub')


#################################SAUMYA CODE STARTS#####################################################################


#driver = webdriver.Chrome(chrome_options=options)
#driver.get('http://cms.nic.in/ncdrcusersWeb/search.do?method=loadSearchPub')

dtof = driver.find_element_by_id("dtof")
dtof.click()
startd="1/1/"
endd="31/12/"
sdate=driver.find_element_by_id("stDate")
edate=driver.find_element_by_id("endDate")
#year  logic
for year in range(2004,2019):

    book = Workbook()
    template_name = 'Confonet-'+str(year)+'.xlsx'
    print('The generated name is '+template_name)
    book.save(template_name)

    title_row = ['CaseNo','Complainant','Respondent','CompAdvocate','RespAdvocate','DOF','DOD','DOU','GetPDF','Year','State','District']
            
    wb = openpyxl.load_workbook(template_name)
    page = wb.active
    page.title = 'Template'
    page.append(title_row)
      
    wb.save(template_name)


    sdate.clear()
    sdate.send_keys(startd+str(year))
    driver.implicitly_wait(100)
    #close=driver.find_element_by_xpath('/html/body/div/div/div[3]/a[2]').click()
    edate=driver.find_element_by_id("endDate")
    edate.clear()
    edate.send_keys(endd+str(year))
    driver.implicitly_wait(100)
    #close=driver.find_element_by_xpath('/html/body/div/div/div[3]/a[2]').click()
     #Search in logic for state and district 
    driver.find_element_by_xpath('//*[@id="searchBy"]/option[8]').click()
    statelist=driver.find_element_by_xpath('//*[@id="stateId"]').click()
    state=Select(driver.find_element_by_id('stateId'))
    stoptions=state.options
    #Range is from 0 to length-1, but issue occurs for states with only 1 district , like Circuit bench amravati,error: Message: Could not locate element with index 1
    for stindex in range(0,len(stoptions)):
        state.select_by_index(stindex)
        driver.implicitly_wait(2000)
        current_state =state.first_selected_option
        print('Current State -- '+current_state.text)
        #districtlist=driver.find_element_by_xpath('//*[@id="districtId"]').click() Venky commented
        driver.implicitly_wait(2000)
        select_district=Select(driver.find_element_by_id('districtId')) # Venky changed element to elements
        dtoptions=select_district.options
        driver.implicitly_wait(2000) #Added by Venky
        #print(dtoptions.text)
##        for j in dtoptions:
##              print(j)
        #sometimes the loop fails with Message: stale element reference: element is not attached to the page document
        for index in range(0,len(dtoptions)):
            try:
                  print('The new district index is '+str(index))
                  print(len(dtoptions))
                  driver.implicitly_wait(1000)
                  select_district.select_by_index(index)
                  driver.implicitly_wait(1000)
                  current_district = select_district.first_selected_option

                  #print('Current District -- '+current_district.text)
                  #Category dropdown
                  #categorylist = driver.find_element_by_xpath('//*[@id="categoryId"]').click()
                  
                  driver.implicitly_wait(500)
                  catselect=Select(driver.find_element_by_id('categoryId'))
                  ctoptions = catselect.options
                  for ind in range(1,len(ctoptions)):
                        driver.implicitly_wait(500)
                        catselect.select_by_index(ind)
                        cat_opt=catselect.first_selected_option
                        print(cat_opt.text)
                        #driver.find_element_by_id("searchImg").click() commented by Venky
                        driver.find_element_by_id("searchbutton").click() #added by Venky
                        driver.implicitly_wait(2000)
            except:
                  print('Failed District -- '+current_district.text)
                  print('Failed District in State '+current_state.text)
                  




#################################SAUMYA CODE ENDS#######################################################################


##      book = Workbook()
##      template_name = 'Confonet-'+str(year)+'.xlsx'
##      print('The generated name is '+template_name)
##      book.save(template_name)
##
##      title_row = ['CaseNo','Complainant','Respondent','CompAdvocate','RespAdvocate','DOF','DOD','DOU','GetPDF']
##            
##      wb = openpyxl.load_workbook(template_name)
##      page = wb.active
##      page.title = 'Template'
##      page.append(title_row)
##      
##      wb.save(template_name)
      
##-----------------------------------TEMP COMMENTING------------------------------
##            
##      for i in range(1,150):
##            print('New Loop, page no '+str(i))
##
##            table = driver.find_element_by_xpath('//*[@id="placeholder1"]/table/tbody')
##            conf_list = []
##            line = []
##            for row in table.find_elements_by_xpath('./tr'):
##                   line = []
##                   for col in row.find_elements_by_xpath('./td'):
##                        name = col.text
##                        line.append(name)
##                   conf_list.append(line)
##                   #print('Row Done')
##
##            del conf_list[0]
##            #print('Printing conf_list')
##            #print(conf_list)
##            wb = openpyxl.load_workbook(template_name)
##            page = wb.active
##            for row in conf_list:
##                  page.append(row)
##            wb.save(template_name)
##            
##            print('Done for page no '+str(i))
##            print('Attempting to click the next if it exists')
##
##            try:
##
##               next_link = driver.find_element_by_link_text('Next')
##               next_link.click()
##               print('Successfully clicked next')
##               #time.sleep(15)
##               driver.implicitly_wait(20)
##
##            except:
##               print('Seems last page is reached...moving to the next combo')
##               break
##            print('End of loop with page no '+str(i+1))



print('end of program')






      



